### ISSUE TITLE
Need instructions for using this

### ISSUE THREAD

**Issue by kandyman2017** [jensechu/kanji#22]
I am a complete beginner to github and I have no background with code whatsoever. Basically, I have absolutely no idea how to use things on Github. But I would love to know how to make customizable, printable kanji sheets.

Sorry but could you explain how to do it in really really basic terms? What do I do with these files? How do I make these printable sheets?

**Comment by jensechu** [comment]
Great question! You can actually go to http://jensechu.github.io/kanji/ and use the app there. :) 

If you hit ctrl+p it will format the site as a worksheet for printing! Welcome to github!

**Comment by jensechu** [comment]
Let me know if everything works out well for you @kandyman2017 👍 Happy to help.

**Comment by kandyman2017** [comment]
I am experimenting with it now. Is there a way to edit the English meanings? If I want to cut down the English definitions to one or two basic words?

**Comment by kandyman2017** [comment]
Also, is there a way to re-order the kanji once you have selected them? Or do you have to start again (if you select the wrong kanji, for example)?

**Comment by jensechu** [comment]
You can deselect the kanji by clicking on it again in the sidebar.

Those are good feature suggestions but at this point they are not supported. Perhaps in the future I'll add that. 🎊

**Comment by kandyman2017** [comment]
Maybe this is a rude question, but is there a way to remove the website link from the printed sheet? I understand if you prefer to have it there, but I am just curious. No offence intended.

**Comment by kandyman2017** [comment]
Even if it's not possible, you've done a great job with these sheets. Thank you for your hard work.

**Comment by jensechu** [comment]
Not rude at all! That is actually added by your operating system not me. I think there should be an option to not include it: http://smallbusiness.chron.com/remove-address-printing-45661.html

I wouldn't want it there either. :D 

Thanks for using it!

**Comment by kandyman2017** [comment]
Great thanks !
